# UI Related
OF_SCREEN_H := 2400
OF_STATUS_INDENT_LEFT := 50
OF_STATUS_INDENT_RIGHT := 50
OF_CLOCK_POS := 1
OF_ALLOW_DISABLE_NAVBAR := 0

# Partition tools
OF_ENABLE_ALL_PARTITION_TOOLS := 1

# Casefolding
OF_FORCE_CASEFOLDING := 1

# Keymaster
OF_DEFAULT_KEYMASTER_VERSION := 4.1

# AIDL Boot HAL
OF_USE_AIDL_BOOT_CONTROL := 1

# Additional configs
OF_SUPPORT_VBMETA_AVB2_PATCHING := 1
OF_FORCE_PREBUILT_KERNEL := 1
OF_USE_GREEN_LED := 0

# Flashlight
OF_FLASHLIGHT_ENABLE := 1

OF_MAINTAINER := Luv <3
